# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e80c36ea78e4942d4d1c08f8adf50187f0e5202d4a1f8055bd3d22c3abcc957b78f9b2af8b8507354c026262c207d71c028fcc1310204f92c82b0f97e8b02f6

test:
  secret_key_base: 35695b073c59d33fad69eb0a22a168beb83475cdef51e9f9006b2beb18f43810daef27abae94aa33453e2102ad631d2737d57970ea8d24280cc3c0dac5301dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
